// Single source of truth for the Premier League player database, shared
// by myxi.html and admin.html. Previously each page kept its own hardcoded
// copy of playersByPos, which had to be manually kept in sync by hand on
// every transfer-window edit - exactly the kind of thing that drifts out
// of sync (as happened more than once). Edit this file only, going
// forward, and both pages pick up the change automatically.
(function () {
  const playersByPos = {
    GK: [
      "Arsenal", "Aston Villa", "Bournemouth", "Brentford", "Brighton",
      "Chelsea", "Coventry", "Crystal Palace", "Everton", "Fulham",
      "Hull", "Ipswich", "Leeds", "Liverpool", "Man City",
      "Man Utd", "Newcastle", "Nott'm Forest", "Sunderland", "Spurs"
    ],
    DEF: [
      { name: "Saliba", club: "Arsenal" }, { name: "Konsa", club: "Arsenal" }, { name: "Gabriel", club: "Arsenal" }, { name: "White", club: "Arsenal" }, { name: "Calafiori", club: "Arsenal" }, { name: "Hincapie", club: "Arsenal" }, { name: "Timber", club: "Arsenal" },  { name: "C Mosquera", club: "Arsenal" }, { name: "Lewis-Skelly", club: "Arsenal" },
      { name: "Pau Torres", club: "Aston Villa" }, { name: "Maatsen", club: "Aston Villa" }, { name: "Cash", club: "Aston Villa" }, { name: "Lindelof", club: "Aston Villa" }, { name: "Mings", club: "Aston Villa" },{ name: "Wan-Bissaka", club: "Aston Villa"},
      { name: "Araujo", club: "Bournemouth" }, { name: "Antonio Silva", club: "Bournemouth" }, { name: "A Smith", club: "Bournemouth" }, { name: "Hill", club: "Bournemouth" }, { name: "Truffert", club: "Bournemouth" }, { name: "Diakite", club: "Bournemouth" }, { name: "Soler", club: "Bournemouth" }, { name: "Milosavljevic", club: "Bournemouth" },
      { name: "Henry", club: "Brentford" }, { name: "Collins", club: "Brentford" }, { name: "Diouf", club: "Brentford" }, { name: "Van den Berg", club: "Brentford" }, { name: "Kayode", club: "Brentford" }, { name: "Ajer", club: "Brentford" }, { name: "Ji-Soo", club: "Brentford" }, { name: "Lewis-Potter", club: "Brentford" }, { name: "Hickey", club: "Brentford" },
      { name: "Dunk", club: "Brighton" }, { name: "Svoboda", club: "Brighton" }, { name: "Vuskovic", club: "Brighton" }, { name: "Kadioglu", club: "Brighton" }, { name: "Hadjam", club: "Brighton" }, { name: "De Cuyper", club: "Brighton" }, { name: "Wieffer", club: "Brighton" }, { name: "Struijk", club: "Brighton" }, { name: "Igor Julio", club: "Brighton" }, { name: "Boscagli", club: "Brighton" }, { name: "Costinha", club: "Brighton" },
      { name: "Colwill", club: "Chelsea" }, { name: "Fofana", club: "Chelsea" }, { name: "Lacroix", club: "Chelsea" }, { name: "James", club: "Chelsea" }, { name: "Sarr", club: "Chelsea" }, { name: "Gusto", club: "Chelsea" }, { name: "Chavarria", club: "Chelsea" }, { name: "Hato", club: "Chelsea" }, { name: "Chalobah", club: "Chelsea" }, { name: "Badiashile", club: "Chelsea" }, { name: "Acheampong", club: "Chelsea" }, { name: "Anselmino", club: "Chelsea" },
      { name: "Amenda", club: "Coventry" }, { name: "DaSilva", club: "Coventry" }, { name: "Pinnock", club: "Coventry" }, { name: "Van Ewijk", club: "Coventry" }, { name: "Latibeaudiere", club: "Coventry" }, { name: "Thomas", club: "Coventry" }, { name: "Kitching", club: "Coventry" }, { name: "Woolfenden", club: "Coventry" }, { name: "Bidwell", club: "Coventry" },
      { name: "Richards", club: "Crystal Palace" }, { name: "Disasi", club: "Crystal Palace" }, { name: "Mitchell", club: "Crystal Palace" }, { name: "Canvot", club: "Crystal Palace" }, { name: "Clyne", club: "Crystal Palace" }, { name: "Sosa", club: "Crystal Palace" }, { name: "Mingueza", club: "Crystal Palace" }, { name: "Riad", club: "Crystal Palace" }, { name: "Tomiyasu", club: "Crystal Palace" },
      { name: "Aznou", club: "Everton" }, { name: "Mykolenko", club: "Everton" }, { name: "Branthwaite", club: "Everton" }, { name: "Tarkowski", club: "Everton" }, { name: "O'Brien", club: "Everton" }, { name: "Patterson", club: "Everton" }, { name: "Keane", club: "Everton" },
      { name: "Andersen", club: "Fulham" }, { name: "Robinson", club: "Fulham" }, { name: "Bassey", club: "Fulham" }, { name: "Tete", club: "Fulham" }, { name: "Castagne", club: "Fulham" }, { name: "Sessengnon", club: "Fulham" }, { name: "Cuenca", club: "Fulham" },
      { name: "Ajayi", club: "Hull" }, { name: "Targett", club: "Hull" }, { name: "Hughes", club: "Hull" }, { name: "Egan", club: "Hull" }, { name: "McNair", club: "Hull" }, { name: "Drameh", club: "Hull" }, { name: "Mendy", club: "Hull" }, { name: "Coyle", club: "Hull" }, { name: "Giles", club: "Hull" }, { name: "Herrington", club: "Hull" },
      { name: "Diop", club: "Ipswich" }, { name: "Furlong", club: "Ipswich" }, { name: "Davis", club: "Ipswich" }, { name: "O'Shea", club: "Ipswich" }, { name: "Kipre", club: "Ipswich" }, { name: "Johnson", club: "Ipswich" }, { name: "Greaves", club: "Ipswich" },
      { name: "Rodon", club: "Leeds" },{ name: "Elvedi", club: "Leeds" }, { name: "Ampadu", club: "Leeds" }, { name: "Muharemovic", club: "Leeds" }, { name: "Bijol", club: "Leeds" }, { name: "Gudmundsson", club: "Leeds" }, { name: "Justin", club: "Leeds" }, { name: "Bogle", club: "Leeds" }, { name: "Bornauw", club: "Leeds" }, { name: "Byram", club: "Leeds" },
      { name: "Van Dijk", club: "Liverpool" }, { name: "R Araujo", club: "Liverpool" }, { name: "Kerkez", club: "Liverpool" }, { name: "Bradley", club: "Liverpool" }, { name: "J Gomez", club: "Liverpool" }, { name: "Frimpong", club: "Liverpool" }, { name: "Tsimikas", club: "Liverpool" }, { name: "Jacquet", club: "Liverpool" }, { name: "Leoni", club: "Liverpool" },
      { name: "Gvardiol", club: "Man City" }, { name: "Khusanov", club: "Man City" }, { name: "Dias", club: "Man City" }, { name: "O'Reilly", club: "Man City" }, { name: "Guehi", club: "Man City" }, { name: "Ait-Nouri", club: "Man City" }, { name: "Nunes", club: "Man City" }, { name: "Rico Lewis", club: "Man City" }, { name: "Reis", club: "Man City" }, { name: "Alleyne", club: "Man City" },
      { name: "Martinez", club: "Man Utd" }, { name: "De Ligt", club: "Man Utd" }, { name: "Dalot", club: "Man Utd" }, { name: "Yoro", club: "Man Utd" }, { name: "Shaw", club: "Man Utd" }, { name: "Maguire", club: "Man Utd" }, { name: "Heaven", club: "Man Utd" }, { name: "Mazraoui", club: "Man Utd" },
      { name: "Schar", club: "Newcastle" }, { name: "Botman", club: "Newcastle" }, { name: "Hall", club: "Newcastle" }, { name: "Burn", club: "Newcastle" }, { name: "Dedic", club: "Newcastle" }, { name: "Thiaw", club: "Newcastle" }, { name: "Livramento", club: "Newcastle" },
      { name: "Murillo", club: "Nott'm Forest" }, { name: "Milenkovic", club: "Nott'm Forest" }, { name: "Munoz", club: "Nott'm Forest" }, { name: "Aina", club: "Nott'm Forest" }, { name: "Williams", club: "Nott'm Forest" }, { name: "Morato", club: "Nott'm Forest" }, { name: "Jair", club: "Nott'm Forest" }, { name: "Savona", club: "Nott'm Forest" }, { name: "Netz", club: "Nott'm Forest" },
      { name: "O'Nien", club: "Sunderland" }, { name: "Hume", club: "Sunderland" }, { name: "Ballard", club: "Sunderland" }, { name: "Alderete", club: "Sunderland" }, { name: "Mukiele", club: "Sunderland" }, { name: "Masuaku", club: "Sunderland" }, { name: "Mandava", club: "Sunderland" }, { name: "Meunier", club: "Sunderland" },
      { name: "Romero", club: "Spurs" }, { name: "Robertson", club: "Spurs" }, { name: "Van de Ven", club: "Spurs" }, { name: "Porro", club: "Spurs" }, { name: "Udogie", club: "Spurs" }, { name: "Danso", club: "Spurs" }, { name: "Senesi", club: "Spurs" }, { name: "Van Hecke", club: "Spurs" }, { name: "Souza", club: "Spurs" },
    ],
    MID: [
      { name: "Odegaard", club: "Arsenal" }, { name: "B Guimaraes", club: "Arsenal" }, { name: "Rice", club: "Arsenal" }, { name: "Saka", club: "Arsenal" }, { name: "Eze", club: "Arsenal" }, { name: "Madueke", club: "Arsenal" }, { name: "Zubimendi", club: "Arsenal" }, { name: "Merino", club: "Arsenal" }, { name: "Dowman", club: "Arsenal" }, { name: "Nwaneri", club: "Arsenal" }, { name: "Tzolis", club: "Arsenal" },
      { name: "Joao Gomes", club: "Aston Villa" }, { name: "Goretzka", club: "Aston Villa" }, { name: "Hemmings", club: "Aston Villa" }, { name: "Ruggeri", club: "Aston Villa" }, { name: "Manzambi", club: "Aston Villa" }, { name: "Garnacho", club: "Aston Villa" }, { name: "McGinn", club: "Aston Villa" }, { name: "Barkley", club: "Aston Villa" }, { name: "Bogarde", club: "Aston Villa" }, { name: "Alysson", club: "Aston Villa" }, { name: "Onana", club: "Aston Villa" }, { name: "Kamara", club: "Aston Villa" }, { name: "Buendia", club: "Aston Villa" }, { name: "Bailey", club: "Aston Villa" },
      { name: "Brooks", club: "Bournemouth" }, { name: "Cook", club: "Bournemouth" }, { name: "Tavernier", club: "Bournemouth" }, { name: "Toth", club: "Bournemouth" }, { name: "Rayan", club: "Bournemouth" }, { name: "Scott", club: "Bournemouth" }, { name: "Doak", club: "Bournemouth" }, { name: "Christie", club: "Bournemouth" }, { name: "Adams", club: "Bournemouth" }, { name: "Adli", club: "Bournemouth" }, { name: "Kluivert", club: "Bournemouth" },
      { name: "Ouattara", club: "Brentford" }, { name: "M Sangare", club: "Brentford" }, { name: "Schade", club: "Brentford" }, { name: "Damsgaard", club: "Brentford" }, { name: "Jensen", club: "Brentford" }, { name: "Yarmoliuk", club: "Brentford" }, { name: "Henderson", club: "Brentford" }, { name: "Janelt", club: "Brentford" }, { name: "Milambo", club: "Brentford" }, { name: "Anthony", club: "Brentford" },
      { name: "Mitoma", club: "Brighton" },{ name: "Minteh", club: "Brighton" }, { name: "Gross", club: "Brighton" }, { name: "Milner", club: "Brighton" }, { name: "Yalcouye", club: "Brighton" }, { name: "Osman", club: "Brighton" },{ name: "D Gomez", club: "Brighton" }, { name: "Ayari", club: "Brighton" }, { name: "Hinshelwood", club: "Brighton" }, { name: "Buonanotte", club: "Brighton" }, { name: "O'Riley", club: "Brighton" },
      { name: "Palmer", club: "Chelsea" }, { name: "Caicedo", club: "Chelsea" }, { name: "Fernandez", club: "Chelsea" }, { name: "Neto", club: "Chelsea" }, { name: "Lavia", club: "Chelsea" }, { name: "Rogers", club: "Chelsea" }, { name: "Estevao", club: "Chelsea" }, { name: "Barco", club: "Chelsea" }, { name: "Gittens", club: "Chelsea" }, { name: "Quenda", club: "Chelsea" }, { name: "Mudryk", club: "Chelsea" },       
      { name: "Onyeka", club: "Coventry" }, { name: "Ephron", club: "Coventry" }, { name: "Sakamoto", club: "Coventry" }, { name: "Mason-Clarke", club: "Coventry" }, { name: "Rudoni", club: "Coventry" }, { name: "Torp", club: "Coventry" }, { name: "Grimes", club: "Coventry" }, { name: "Eccles", club: "Coventry" }, { name: "Yirenkyi", club: "Coventry" }, { name: "Hamer", club: "Coventry" },
      { name: "I Sarr", club: "Crystal Palace" }, { name: "Gozo", club: "Crystal Palace" }, { name: "Wharton", club: "Crystal Palace" }, { name: "Kamada", club: "Crystal Palace" }, { name: "Pino", club: "Crystal Palace" }, { name: "Hughes", club: "Crystal Palace" }, { name: "Lerma", club: "Crystal Palace" }, { name: "Doucoure", club: "Crystal Palace" }, { name: "Esse", club: "Crystal Palace" }, { name: "Devenney", club: "Crystal Palace" }, { name: "Khalalli", club: "Crystal Palace" }, { name: "McNeil", club: "Crystal Palace" },
      { name: "B Johnson", club: "Everton" }, { name: "Garner", club: "Everton" }, { name: "Ndiaye", club: "Everton" }, { name: "Dewsbury-Hall", club: "Everton" }, { name: "Alcaraz", club: "Everton" }, { name: "Dibling", club: "Everton" }, { name: "Hackney", club: "Everton" }, { name: "Rohl", club: "Everton" }, { name: "Armstrong", club: "Everton" }, { name: "Iroegbunam", club: "Everton" }, { name: "Norgaard", club: "Everton" },  { name: "George", club: "Everton" },
      { name: "Smith Rowe", club: "Fulham" }, { name: "Charles", club: "Fulham" }, { name: "Palacios", club: "Fulham" }, { name: "Kevin", club: "Fulham" }, { name: "Iwobi", club: "Fulham" }, { name: "Bobb", club: "Fulham" }, { name: "Berge", club: "Fulham" }, { name: "Cairney", club: "Fulham" }, { name: "King", club: "Fulham" }, { name: "Reed", club: "Fulham" },
      { name: "Belloumi", club: "Hull" }, { name: "Cho", club: "Hull" }, { name: "Morita", club: "Hull" }, { name: "Zambrano", club: "Hull" }, { name: "Miller", club: "Hull" }, { name: "Gyabi", club: "Hull" }, { name: "Omar", club: "Hull" }, { name: "Dowell", club: "Hull" }, { name: "Crooks", club: "Hull" }, { name: "Slater", club: "Hull" }, { name: "Gourna-Douath", club: "Hull" }, { name: "Stroud", club: "Hull" },
      { name: "Fatawu", club: "Ipswich" }, { name: "Palacios", club: "Ipswich" }, { name: "Enciso", club: "Ipswich" }, { name: "A Ouattara", club: "Ipswich" }, { name: "Nunez", club: "Ipswich" }, { name: "Lukic", club: "Ipswich" }, { name: "Philogene-Bidace", club: "Ipswich" }, { name: "Clarke", club: "Ipswich" }, { name: "Walle Egeli", club: "Ipswich" }, { name: "Szmodics", club: "Ipswich" }, { name: "Ogbene", club: "Ipswich" }, { name: "McAteer", club: "Ipswich" },
      { name: "Okafor", club: "Leeds" }, { name: "Tanaka", club: "Leeds" }, { name: "Aaronson", club: "Leeds" }, { name: "Longstaff", club: "Leeds" }, { name: "Stach", club: "Leeds" }, { name: "Wilson", club: "Leeds" }, { name: "James", club: "Leeds" }, { name: "Gruev", club: "Leeds" }, { name: "Gnonto", club: "Leeds" },
      { name: "Mac Allister", club: "Liverpool" }, { name: "Munoz", club: "Liverpool" }, { name: "Koumas", club: "Liverpool" }, { name: "Szoboszlai", club: "Liverpool" }, { name: "Gravenberch", club: "Liverpool" }, { name: "Wirtz", club: "Liverpool" }, { name: "Gakpo", club: "Liverpool" }, { name: "Ngumoha", club: "Liverpool" }, { name: "C Jones", club: "Liverpool" }, { name: "Elliot", club: "Liverpool" }, { name: "Endo", club: "Liverpool" },
      { name: "Cherki", club: "Man City" }, { name: "Foden", club: "Man City" }, { name: "Doku", club: "Man City" }, { name: "Semenyo", club: "Man City" }, { name: "Grealish", club: "Man City" }, { name: "Bouaddi", club: "Man City" }, { name: "Kovacic", club: "Man City" }, { name: "Echverri", club: "Man City" }, { name: "Anderson", club: "Man City" },
      { name: "Bruno Fernandes", club: "Man Utd" }, { name: "Baleba", club: "Man Utd" }, { name: "Mainoo", club: "Man Utd" }, { name: "Mbuemo", club: "Man Utd" }, { name: "Diallo", club: "Man Utd" }, { name: "Andrey Santos", club: "Man Utd" }, { name: "Dorgu", club: "Man Utd" }, { name: "Ugarte", club: "Man Utd" }, { name: "Tielemans", club: "Man Utd" }, { name: "Mount", club: "Man Utd" }, { name: "Lacey", club: "Man Utd" },
      { name: "Miley", club: "Newcastle" }, { name: "Murphy", club: "Newcastle" }, { name: "Elanga", club: "Newcastle" }, { name: "Joelinton", club: "Newcastle" }, { name: "Steur", club: "Newcastle" }, { name: "Barnes", club: "Newcastle" }, { name: "Bamba", club: "Newcastle" }, { name: "Toure", club: "Newcastle" }, { name: "Ramsey", club: "Newcastle" }, { name: "Willock", club: "Newcastle" }, { name: "Nico Gonzales", club: "Newcastle" },
      { name: "Gibbs-White", club: "Nott'm Forest" }, { name: "Schlager", club: "Nott'm Forest" }, { name: "Hudson-Odoi", club: "Nott'm Forest" }, { name: "Sangare", club: "Nott'm Forest" }, { name: "Ndoye", club: "Nott'm Forest" }, { name: "McAtee", club: "Nott'm Forest" }, { name: "Dominguez", club: "Nott'm Forest" }, { name: "Hutchinson", club: "Nott'm Forest" }, { name: "Bakwa", club: "Nott'm Forest" },
      { name: "Diarra", club: "Sunderland" }, { name: "Le Fee", club: "Sunderland" }, { name: "Rigg", club: "Sunderland" }, { name: "Xhaka", club: "Sunderland" }, { name: "Adingra", club: "Sunderland" }, { name: "Talbi", club: "Sunderland" }, { name: "Sadiki", club: "Sunderland" }, { name: "Angulo", club: "Sunderland" },
      { name: "Maddison", club: "Spurs" }, { name: "Moore", club: "Spurs" }, { name: "Kulusevski", club: "Spurs" }, { name: "Bentancur", club: "Spurs" }, { name: "Tonali", club: "Spurs" }, { name: "Kudus", club: "Spurs" }, { name: "Savinho", club: "Spurs" }, { name: "Xavi Simons", club: "Spurs" }, { name: "Fernandes", club: "Spurs" }, { name: "Gray", club: "Spurs" }, { name: "Gallagher", club: "Spurs" },
    ],
    FWD: [
      { name: "Havertz", club: "Arsenal" }, { name: "Martinelli", club: "Arsenal" }, { name: "Gyokeres", club: "Arsenal" },
      { name: "Madjo", club: "Aston Villa" }, { name: "Abraham", club: "Aston Villa" }, { name: "Jackson", club: "Aston Villa" },
      { name: "Evanilson", club: "Bournemouth" }, { name: "Junior Kroupi", club: "Bournemouth" }, { name: "Alvaro Rodriguez", club: "Bournemouth" }, { name: "Unal", club: "Bournemouth" }, { name: "Jebbison", club: "Bournemouth" },
      { name: "Thiago", club: "Brentford" }, { name: "Wilson", club: "Brentford" }, { name: "Nunes", club: "Brentford" }, { name: "Furo", club: "Brentford" },
      { name: "Kostoulas", club: "Brighton" }, { name: "Tzimas", club: "Brighton" }, { name: "Ferguson", club: "Brighton" }, { name: "David", club: "Brighton" }, { name: "Yohanna", club: "Brighton" },
      { name: "Joao Pedro", club: "Chelsea" }, { name: "Welbeck", club: "Chelsea" }, { name: "Guiu", club: "Chelsea" }, { name: "Emegha", club: "Chelsea" },
      { name: "Thomas-Asante", club: "Coventry" }, { name: "Wright", club: "Coventry" }, { name: "Tchaouna", club: "Coventry" }, { name: "Simms", club: "Coventry" }, { name: "Awoniyi", club: "Coventry" }, 
      { name: "Mateta", club: "Crystal Palace" }, { name: "Strand-Larsen", club: "Crystal Palace" },  { name: "Guessand", club: "Crystal Palace" }, { name: "Nketiah", club: "Crystal Palace" },
      { name: "Barry", club: "Everton" }, { name: "Beto", club: "Everton" },
      { name: "Kusi-Asare", club: "Fulham" }, { name: "Muniz", club: "Fulham" }, { name: "Garcia", club: "Fulham" },
      { name: "McBurnie", club: "Hull" }, { name: "Burstow", club: "Hull" }, { name: "Destan", club: "Hull" },
      { name: "Al-Hamadi", club: "Ipswich" }, { name: "Maeda", club: "Ipswich" }, { name: "Akpom", club: "Ipswich" },{ name: "Mehmeti", club: "Ipswich" }, { name: "Hirst", club: "Ipswich" }, { name: "Emersonn", club: "Ipswich" },
      { name: "Calvert-Lewin", club: "Leeds" }, { name: "Nmecha", club: "Leeds" },
      { name: "Isak", club: "Liverpool" }, { name: "Ekitike", club: "Liverpool" },
      { name: "Haaland", club: "Man City" },
      { name: "Rashford", club: "Man Utd" }, { name: "Sesko", club: "Man Utd" }, { name: "Cunha", club: "Man Utd" },
      { name: "Wissa", club: "Newcastle" }, { name: "Woltemade", club: "Newcastle" }, { name: "Osula", club: "Newcastle" },
      { name: "Wood", club: "Nott'm Forest" }, { name: "I Jesus", club: "Nott'm Forest" },  { name: "Delap", club: "Nott'm Forest" }, { name: "Kalimuendo", club: "Nott'm Forest" },
      { name: "Isidor", club: "Sunderland" }, { name: "Mayenda", club: "Sunderland" }, { name: "Brobbey", club: "Sunderland" },
      { name: "Richarlison", club: "Spurs" }, { name: "Solanke", club: "Spurs" }, { name: "Tel", club: "Spurs" }, { name: "Marmoush", club: "Spurs" },
    ]
  };

  window.playersByPos = playersByPos;
})();
